sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VNw9eKVZvOAYv7aGjCZjXEh7CNa9FDEp/2D0+jM0lTk3jJYTvTXysJubL4ytaTi+OOhuNkX+rUEWLGJSQm5HHzw/s6lR//Vz8xco/hwsVutWsh096ZJN/+mkx5dFLLZLQvmPBvpHSXdGTDNkhcd4CtXm9szO1D/CdepB52XTf4rHyCdHJoHu1CGfVXbv7L9Qp7idhdX7HcfolPMwVQjZuV39NR+dbUmryycrwl2xiQ7yBmNTjfPP8QUJxQMpPESmaVINVsILwUwKN/6u1hyHc1N8NXmqhz+2yNNSkC7LwYsOGqY2E8jnzCLwxgTUN9oBP6LGN3WirFq+kMnOzg7YoZLY5wtDXaYMb2XKw1caqgQ0Usi+lHdLhKjc0XKRB/jiQoURpZOnEovzMML8FMuLTao95Ke+zNQc4n4yJ7Z97l0LPTCOtra+OC6eM74n/3g4C7R4wBLqI+x8RXyfQj4vK0bLoLY1bDJ5HWVg7NWrLxL6efRlgeg8EdXg4+cg4Z8wfvEtdnTk8rEvg4thAhmFHj2c6P9cqy/6CA/lko6rWLYZOo66+vafcFKeM5o7fHPgQ9Ey9Uy+g6Y8UelTLMc/EhhVdIHoANg4u7XCxmXmHlumQiSTfDHZOT7fnC6g+VX/XUPQQzjlVZGAnMQDSNGVqEZ3Nj3yp9Mifx7M7UUV3ss=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Pathologie-Verbale-ou-Lesions-de-certains-mots-dans-le-cours-de-l-usage_4935
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy